initital vnet char
distributed-technologies/mukube-vnet pull request #1
Opened 2021-02-26 11:01 UTC by jacobcrawford

2021-02-26 11:16 UTC, MartinSchmidt requested changes
Add missing values.schema.json to validate the values file.

2021-02-26 11:16 UTC, MartinSchmidt commented on chart/Chart.yaml
> +  - name: Jacob Crawford
No endline of file!!!!

2021-02-26 11:16 UTC, MartinSchmidt commented on chart/values.yaml
> +weave_npc_image_tag: 2.8.1
No end line!

2021-02-26 11:16 UTC, MartinSchmidt commented on chart/values.yaml
> +IPALLOC_RANGE_VALUES: 172.30.0.0/16
values.yaml file naming not consistent! Some are uppercase and some lower

2021-02-26 11:16 UTC, MartinSchmidt commented on chart/templates/vnet_conf.yaml
> +              "url": "/k8s/v1.16/net.yaml?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiIyMCIsIEdpdFZlcnNpb246InYxLjIwLjIiLCBHaXRDb21taXQ6ImZhZWNiMTk2ODE1ZTI0OGQzZWNmYjAzY
What is this at the end? secret?

2021-03-01 06:14 UTC, jacobcrawford commented on chart/templates/vnet_conf.yaml
> +              "url": "/k8s/v1.16/net.yaml?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiIyMCIsIEdpdFZlcnNpb246InYxLjIwLjIiLCBHaXRDb21taXQ6ImZhZWNiMTk2ODE1ZTI0OGQzZWNmYjAzY
It is the url where the .yaml file was requested. The string is base64 encoding of the k8s-version.

2021-03-02 07:31 UTC, MartinSchmidt approved these changes

2021-03-02 07:35 UTC, merged