Create blank.yml
distributed-technologies/mukube-vnet pull request #2
Opened 2021-03-02 07:54 UTC by jacobcrawford

2021-03-05 06:49 UTC, MartinSchmidt requested changes

2021-03-05 06:49 UTC, MartinSchmidt commented on chart/values.yaml
> +weave_npc_image_tag: 2.8.1
- [ ] missing empty line

2021-03-05 06:49 UTC, MartinSchmidt commented on .github/workflows/bump_version.yaml
> +        VERBOSE: true
- [ ] missing empty line

2021-03-05 06:49 UTC, MartinSchmidt commented on .github/workflows/build_release.yml
> +    if: ${{ github.event.workflow_run.conclusion == 'success' }}
does it still run if a version tag is set manually?

2021-03-08 11:05 UTC, jacobcrawford commented on .github/workflows/build_release.yml
> +    if: ${{ github.event.workflow_run.conclusion == 'success' }}
Bug is fixed and pushed to wiki

2021-03-08 11:47 UTC, MartinSchmidt approved these changes

2021-03-08 11:57 UTC, merged